//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace PKXCMS.Model
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class PKXCMSEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“PKXCMSEntities”部分中的连接字符串初始化新 PKXCMSEntities 对象。
        /// </summary>
        public PKXCMSEntities() : base("name=PKXCMSEntities", "PKXCMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 PKXCMSEntities 对象。
        /// </summary>
        public PKXCMSEntities(string connectionString) : base(connectionString, "PKXCMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 PKXCMSEntities 对象。
        /// </summary>
        public PKXCMSEntities(EntityConnection connection) : base(connection, "PKXCMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tblForum> tblForum
        {
            get
            {
                if ((_tblForum == null))
                {
                    _tblForum = base.CreateObjectSet<tblForum>("tblForum");
                }
                return _tblForum;
            }
        }
        private ObjectSet<tblForum> _tblForum;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tblMessage> tblMessage
        {
            get
            {
                if ((_tblMessage == null))
                {
                    _tblMessage = base.CreateObjectSet<tblMessage>("tblMessage");
                }
                return _tblMessage;
            }
        }
        private ObjectSet<tblMessage> _tblMessage;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tblNavMenu> tblNavMenu
        {
            get
            {
                if ((_tblNavMenu == null))
                {
                    _tblNavMenu = base.CreateObjectSet<tblNavMenu>("tblNavMenu");
                }
                return _tblNavMenu;
            }
        }
        private ObjectSet<tblNavMenu> _tblNavMenu;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tblPost> tblPost
        {
            get
            {
                if ((_tblPost == null))
                {
                    _tblPost = base.CreateObjectSet<tblPost>("tblPost");
                }
                return _tblPost;
            }
        }
        private ObjectSet<tblPost> _tblPost;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tblSystem> tblSystem
        {
            get
            {
                if ((_tblSystem == null))
                {
                    _tblSystem = base.CreateObjectSet<tblSystem>("tblSystem");
                }
                return _tblSystem;
            }
        }
        private ObjectSet<tblSystem> _tblSystem;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tblUser> tblUser
        {
            get
            {
                if ((_tblUser == null))
                {
                    _tblUser = base.CreateObjectSet<tblUser>("tblUser");
                }
                return _tblUser;
            }
        }
        private ObjectSet<tblUser> _tblUser;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 tblForum EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotblForum(tblForum tblForum)
        {
            base.AddObject("tblForum", tblForum);
        }
    
        /// <summary>
        /// 用于向 tblMessage EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotblMessage(tblMessage tblMessage)
        {
            base.AddObject("tblMessage", tblMessage);
        }
    
        /// <summary>
        /// 用于向 tblNavMenu EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotblNavMenu(tblNavMenu tblNavMenu)
        {
            base.AddObject("tblNavMenu", tblNavMenu);
        }
    
        /// <summary>
        /// 用于向 tblPost EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotblPost(tblPost tblPost)
        {
            base.AddObject("tblPost", tblPost);
        }
    
        /// <summary>
        /// 用于向 tblSystem EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotblSystem(tblSystem tblSystem)
        {
            base.AddObject("tblSystem", tblSystem);
        }
    
        /// <summary>
        /// 用于向 tblUser EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotblUser(tblUser tblUser)
        {
            base.AddObject("tblUser", tblUser);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PKXCMSModel", Name="tblForum")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblForum : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tblForum 对象。
        /// </summary>
        /// <param name="forumID">ForumID 属性的初始值。</param>
        public static tblForum CreatetblForum(global::System.Int32 forumID)
        {
            tblForum tblForum = new tblForum();
            tblForum.ForumID = forumID;
            return tblForum;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ForumID
        {
            get
            {
                return _ForumID;
            }
            set
            {
                if (_ForumID != value)
                {
                    OnForumIDChanging(value);
                    ReportPropertyChanging("ForumID");
                    _ForumID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ForumID");
                    OnForumIDChanged();
                }
            }
        }
        private global::System.Int32 _ForumID;
        partial void OnForumIDChanging(global::System.Int32 value);
        partial void OnForumIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ForumName
        {
            get
            {
                return _ForumName;
            }
            set
            {
                OnForumNameChanging(value);
                ReportPropertyChanging("ForumName");
                _ForumName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ForumName");
                OnForumNameChanged();
            }
        }
        private global::System.String _ForumName;
        partial void OnForumNameChanging(global::System.String value);
        partial void OnForumNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ForumIcon
        {
            get
            {
                return _ForumIcon;
            }
            set
            {
                OnForumIconChanging(value);
                ReportPropertyChanging("ForumIcon");
                _ForumIcon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ForumIcon");
                OnForumIconChanged();
            }
        }
        private global::System.String _ForumIcon;
        partial void OnForumIconChanging(global::System.String value);
        partial void OnForumIconChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PForumID
        {
            get
            {
                return _PForumID;
            }
            set
            {
                OnPForumIDChanging(value);
                ReportPropertyChanging("PForumID");
                _PForumID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PForumID");
                OnPForumIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PForumID;
        partial void OnPForumIDChanging(Nullable<global::System.Int32> value);
        partial void OnPForumIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ForumDescribe
        {
            get
            {
                return _ForumDescribe;
            }
            set
            {
                OnForumDescribeChanging(value);
                ReportPropertyChanging("ForumDescribe");
                _ForumDescribe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ForumDescribe");
                OnForumDescribeChanged();
            }
        }
        private global::System.String _ForumDescribe;
        partial void OnForumDescribeChanging(global::System.String value);
        partial void OnForumDescribeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PKXCMSModel", Name="tblMessage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblMessage : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tblMessage 对象。
        /// </summary>
        /// <param name="mID">MID 属性的初始值。</param>
        public static tblMessage CreatetblMessage(global::System.Int32 mID)
        {
            tblMessage tblMessage = new tblMessage();
            tblMessage.MID = mID;
            return tblMessage;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MID
        {
            get
            {
                return _MID;
            }
            set
            {
                if (_MID != value)
                {
                    OnMIDChanging(value);
                    ReportPropertyChanging("MID");
                    _MID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MID");
                    OnMIDChanged();
                }
            }
        }
        private global::System.Int32 _MID;
        partial void OnMIDChanging(global::System.Int32 value);
        partial void OnMIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MContent
        {
            get
            {
                return _MContent;
            }
            set
            {
                OnMContentChanging(value);
                ReportPropertyChanging("MContent");
                _MContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MContent");
                OnMContentChanged();
            }
        }
        private global::System.String _MContent;
        partial void OnMContentChanging(global::System.String value);
        partial void OnMContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MIP
        {
            get
            {
                return _MIP;
            }
            set
            {
                OnMIPChanging(value);
                ReportPropertyChanging("MIP");
                _MIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MIP");
                OnMIPChanged();
            }
        }
        private global::System.String _MIP;
        partial void OnMIPChanging(global::System.String value);
        partial void OnMIPChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MDate
        {
            get
            {
                return _MDate;
            }
            set
            {
                OnMDateChanging(value);
                ReportPropertyChanging("MDate");
                _MDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MDate");
                OnMDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _MDate;
        partial void OnMDateChanging(Nullable<global::System.DateTime> value);
        partial void OnMDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MName
        {
            get
            {
                return _MName;
            }
            set
            {
                OnMNameChanging(value);
                ReportPropertyChanging("MName");
                _MName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MName");
                OnMNameChanged();
            }
        }
        private global::System.String _MName;
        partial void OnMNameChanging(global::System.String value);
        partial void OnMNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PKXCMSModel", Name="tblNavMenu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblNavMenu : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tblNavMenu 对象。
        /// </summary>
        /// <param name="navID">NavID 属性的初始值。</param>
        public static tblNavMenu CreatetblNavMenu(global::System.Int32 navID)
        {
            tblNavMenu tblNavMenu = new tblNavMenu();
            tblNavMenu.NavID = navID;
            return tblNavMenu;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NavID
        {
            get
            {
                return _NavID;
            }
            set
            {
                if (_NavID != value)
                {
                    OnNavIDChanging(value);
                    ReportPropertyChanging("NavID");
                    _NavID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NavID");
                    OnNavIDChanged();
                }
            }
        }
        private global::System.Int32 _NavID;
        partial void OnNavIDChanging(global::System.Int32 value);
        partial void OnNavIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NavName
        {
            get
            {
                return _NavName;
            }
            set
            {
                OnNavNameChanging(value);
                ReportPropertyChanging("NavName");
                _NavName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NavName");
                OnNavNameChanged();
            }
        }
        private global::System.String _NavName;
        partial void OnNavNameChanging(global::System.String value);
        partial void OnNavNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NavUrl
        {
            get
            {
                return _NavUrl;
            }
            set
            {
                OnNavUrlChanging(value);
                ReportPropertyChanging("NavUrl");
                _NavUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NavUrl");
                OnNavUrlChanged();
            }
        }
        private global::System.String _NavUrl;
        partial void OnNavUrlChanging(global::System.String value);
        partial void OnNavUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NavSort
        {
            get
            {
                return _NavSort;
            }
            set
            {
                OnNavSortChanging(value);
                ReportPropertyChanging("NavSort");
                _NavSort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NavSort");
                OnNavSortChanged();
            }
        }
        private Nullable<global::System.Int32> _NavSort;
        partial void OnNavSortChanging(Nullable<global::System.Int32> value);
        partial void OnNavSortChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PNavID
        {
            get
            {
                return _PNavID;
            }
            set
            {
                OnPNavIDChanging(value);
                ReportPropertyChanging("PNavID");
                _PNavID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PNavID");
                OnPNavIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PNavID;
        partial void OnPNavIDChanging(Nullable<global::System.Int32> value);
        partial void OnPNavIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NavLayer
        {
            get
            {
                return _NavLayer;
            }
            set
            {
                OnNavLayerChanging(value);
                ReportPropertyChanging("NavLayer");
                _NavLayer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NavLayer");
                OnNavLayerChanged();
            }
        }
        private Nullable<global::System.Int32> _NavLayer;
        partial void OnNavLayerChanging(Nullable<global::System.Int32> value);
        partial void OnNavLayerChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PKXCMSModel", Name="tblPost")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblPost : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tblPost 对象。
        /// </summary>
        /// <param name="postID">PostID 属性的初始值。</param>
        public static tblPost CreatetblPost(global::System.Int32 postID)
        {
            tblPost tblPost = new tblPost();
            tblPost.PostID = postID;
            return tblPost;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PostID
        {
            get
            {
                return _PostID;
            }
            set
            {
                if (_PostID != value)
                {
                    OnPostIDChanging(value);
                    ReportPropertyChanging("PostID");
                    _PostID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PostID");
                    OnPostIDChanged();
                }
            }
        }
        private global::System.Int32 _PostID;
        partial void OnPostIDChanging(global::System.Int32 value);
        partial void OnPostIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostTitle
        {
            get
            {
                return _PostTitle;
            }
            set
            {
                OnPostTitleChanging(value);
                ReportPropertyChanging("PostTitle");
                _PostTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PostTitle");
                OnPostTitleChanged();
            }
        }
        private global::System.String _PostTitle;
        partial void OnPostTitleChanging(global::System.String value);
        partial void OnPostTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostContent
        {
            get
            {
                return _PostContent;
            }
            set
            {
                OnPostContentChanging(value);
                ReportPropertyChanging("PostContent");
                _PostContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PostContent");
                OnPostContentChanged();
            }
        }
        private global::System.String _PostContent;
        partial void OnPostContentChanging(global::System.String value);
        partial void OnPostContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PostDate
        {
            get
            {
                return _PostDate;
            }
            set
            {
                OnPostDateChanging(value);
                ReportPropertyChanging("PostDate");
                _PostDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostDate");
                OnPostDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PostDate;
        partial void OnPostDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPostDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostImage
        {
            get
            {
                return _PostImage;
            }
            set
            {
                OnPostImageChanging(value);
                ReportPropertyChanging("PostImage");
                _PostImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PostImage");
                OnPostImageChanged();
            }
        }
        private global::System.String _PostImage;
        partial void OnPostImageChanging(global::System.String value);
        partial void OnPostImageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ForumID
        {
            get
            {
                return _ForumID;
            }
            set
            {
                OnForumIDChanging(value);
                ReportPropertyChanging("ForumID");
                _ForumID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ForumID");
                OnForumIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ForumID;
        partial void OnForumIDChanging(Nullable<global::System.Int32> value);
        partial void OnForumIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ForumName
        {
            get
            {
                return _ForumName;
            }
            set
            {
                OnForumNameChanging(value);
                ReportPropertyChanging("ForumName");
                _ForumName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ForumName");
                OnForumNameChanged();
            }
        }
        private global::System.String _ForumName;
        partial void OnForumNameChanging(global::System.String value);
        partial void OnForumNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PKXCMSModel", Name="tblSystem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSystem : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tblSystem 对象。
        /// </summary>
        /// <param name="sysID">SysID 属性的初始值。</param>
        public static tblSystem CreatetblSystem(global::System.Int32 sysID)
        {
            tblSystem tblSystem = new tblSystem();
            tblSystem.SysID = sysID;
            return tblSystem;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SysID
        {
            get
            {
                return _SysID;
            }
            set
            {
                if (_SysID != value)
                {
                    OnSysIDChanging(value);
                    ReportPropertyChanging("SysID");
                    _SysID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SysID");
                    OnSysIDChanged();
                }
            }
        }
        private global::System.Int32 _SysID;
        partial void OnSysIDChanging(global::System.Int32 value);
        partial void OnSysIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ListPageSize
        {
            get
            {
                return _ListPageSize;
            }
            set
            {
                OnListPageSizeChanging(value);
                ReportPropertyChanging("ListPageSize");
                _ListPageSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ListPageSize");
                OnListPageSizeChanged();
            }
        }
        private Nullable<global::System.Int32> _ListPageSize;
        partial void OnListPageSizeChanging(Nullable<global::System.Int32> value);
        partial void OnListPageSizeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsRegCodeByPost
        {
            get
            {
                return _IsRegCodeByPost;
            }
            set
            {
                OnIsRegCodeByPostChanging(value);
                ReportPropertyChanging("IsRegCodeByPost");
                _IsRegCodeByPost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRegCodeByPost");
                OnIsRegCodeByPostChanged();
            }
        }
        private Nullable<global::System.Int32> _IsRegCodeByPost;
        partial void OnIsRegCodeByPostChanging(Nullable<global::System.Int32> value);
        partial void OnIsRegCodeByPostChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsRegCodeByMessage
        {
            get
            {
                return _IsRegCodeByMessage;
            }
            set
            {
                OnIsRegCodeByMessageChanging(value);
                ReportPropertyChanging("IsRegCodeByMessage");
                _IsRegCodeByMessage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRegCodeByMessage");
                OnIsRegCodeByMessageChanged();
            }
        }
        private Nullable<global::System.Int32> _IsRegCodeByMessage;
        partial void OnIsRegCodeByMessageChanging(Nullable<global::System.Int32> value);
        partial void OnIsRegCodeByMessageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsRegCodeByLogin
        {
            get
            {
                return _IsRegCodeByLogin;
            }
            set
            {
                OnIsRegCodeByLoginChanging(value);
                ReportPropertyChanging("IsRegCodeByLogin");
                _IsRegCodeByLogin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRegCodeByLogin");
                OnIsRegCodeByLoginChanged();
            }
        }
        private Nullable<global::System.Int32> _IsRegCodeByLogin;
        partial void OnIsRegCodeByLoginChanging(Nullable<global::System.Int32> value);
        partial void OnIsRegCodeByLoginChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsLoginByMessage
        {
            get
            {
                return _IsLoginByMessage;
            }
            set
            {
                OnIsLoginByMessageChanging(value);
                ReportPropertyChanging("IsLoginByMessage");
                _IsLoginByMessage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsLoginByMessage");
                OnIsLoginByMessageChanged();
            }
        }
        private Nullable<global::System.Int32> _IsLoginByMessage;
        partial void OnIsLoginByMessageChanging(Nullable<global::System.Int32> value);
        partial void OnIsLoginByMessageChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PKXCMSModel", Name="tblUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUser : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tblUser 对象。
        /// </summary>
        /// <param name="userID">UserID 属性的初始值。</param>
        public static tblUser CreatetblUser(global::System.Int32 userID)
        {
            tblUser tblUser = new tblUser();
            tblUser.UserID = userID;
            return tblUser;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserState
        {
            get
            {
                return _UserState;
            }
            set
            {
                OnUserStateChanging(value);
                ReportPropertyChanging("UserState");
                _UserState = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserState");
                OnUserStateChanged();
            }
        }
        private Nullable<global::System.Int32> _UserState;
        partial void OnUserStateChanging(Nullable<global::System.Int32> value);
        partial void OnUserStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UserCreateDate
        {
            get
            {
                return _UserCreateDate;
            }
            set
            {
                OnUserCreateDateChanging(value);
                ReportPropertyChanging("UserCreateDate");
                _UserCreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserCreateDate");
                OnUserCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UserCreateDate;
        partial void OnUserCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUserCreateDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RealName
        {
            get
            {
                return _RealName;
            }
            set
            {
                OnRealNameChanging(value);
                ReportPropertyChanging("RealName");
                _RealName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RealName");
                OnRealNameChanged();
            }
        }
        private global::System.String _RealName;
        partial void OnRealNameChanging(global::System.String value);
        partial void OnRealNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sex
        {
            get
            {
                return _Sex;
            }
            set
            {
                OnSexChanging(value);
                ReportPropertyChanging("Sex");
                _Sex = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sex");
                OnSexChanged();
            }
        }
        private global::System.String _Sex;
        partial void OnSexChanging(global::System.String value);
        partial void OnSexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _Age;
        partial void OnAgeChanging(Nullable<global::System.Int32> value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegIP
        {
            get
            {
                return _RegIP;
            }
            set
            {
                OnRegIPChanging(value);
                ReportPropertyChanging("RegIP");
                _RegIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RegIP");
                OnRegIPChanged();
            }
        }
        private global::System.String _RegIP;
        partial void OnRegIPChanging(global::System.String value);
        partial void OnRegIPChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private Nullable<global::System.Int32> _Role;
        partial void OnRoleChanging(Nullable<global::System.Int32> value);
        partial void OnRoleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLoginDate
        {
            get
            {
                return _LastLoginDate;
            }
            set
            {
                OnLastLoginDateChanging(value);
                ReportPropertyChanging("LastLoginDate");
                _LastLoginDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoginDate");
                OnLastLoginDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLoginDate;
        partial void OnLastLoginDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginDateChanged();

        #endregion
    
    }

    #endregion
    
}
